import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ApolloWrapper } from "@/context/ApolloWrapper";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BookShelf",
  description: "Generated by create next app",
};

import { cookies } from "next/headers";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasInitialToken = cookieStore.has("accessToken");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-zinc-950 overscroll-none`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950 overscroll-none text-zinc-50">
        <NextTopLoader
          color="#a855f7"
          showSpinner={false}
          shadow="0 0 10px #a855f7,0 0 5px #a855f7"
        />
        <ApolloWrapper>
          <AuthProvider hasInitialToken={hasInitialToken}>
            {children}
            <Toaster theme="dark" position="bottom-right" />
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
